// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using WPAppStudio.Entities;
using WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// historyCollection data source.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public class historyCollection : IhistoryCollection 
    {
        private readonly ObservableCollection<historyCollectionSchema> _data = new ObservableCollection<historyCollectionSchema>
		{
          new historyCollectionSchema
            {
                Id= new Guid("732fc6a5-a1c5-4f5d-8b7e-d1e8281a6227"),
                Title=@"AZURE MOBILE SERVICES",
                Subtitle=@"Tue Oct 15 at 6pm",
                Image=@"..\Images\Item-f56e699d-fecc-46e8-aef6-02c8362d5acc.png",
                Description=@"FREESTUFF ALERT: Our awesome Nokia Ambassador Bill Reiss is providing free Lumia phone and some more cool DVLUP swag!!!

Pizza and networking starts at 6pm

Shayne Boyer 
Sr Solutions Architect

will be presenting

Azure Mobile Services

Authorization, Push Notifications, RESTful ...OH MY.

Azure Mobile Services is the one tool you want in your bag now. Unfortunately named ""Mobile"" its so much more. Come see how you can leverage this great cloud service platform to give you the backend services you can use for HTML, Windows Phone, Windows 8, and even iOS and Android development.

Shayne Boyer is a Solutions Architect with over 15 years experience working with Microsoft based solutions. He holds MCP Microsoft Certification, is an INETA community speaker, a Telerik MVP and Nokia Developer Champion. Over the past 10 years he has lead development teams working on enterprise solutions with a focus on productivity, performance and sustainability. Shayne often publishes content on ASP.NET, TypeScript, Node.js as well Windows 8 and Windows Phone development and can always be found on twitter @spboyer or on his blog at tattoocoder.com




Location: Blue Cross & Blue Shield, 4800 Deerwood Campus Parkway, Jacksonville, FL",
			},
		};
	
		
        /// <summary>
        /// Retrieves the data from a static data source, in an observable collection of historyCollectionSchema items.
        /// </summary>
        /// <returns>An observable collection of historyCollectionSchema items.</returns>
        public ObservableCollection<historyCollectionSchema> GetData()
        {		
            return _data;
        }
		
		/// <summary>
        /// Retrieves the data from a static data source, filtered by a filter specification, in an observable collection of historyCollectionSchema items.
        /// </summary>
		/// <param name="filter">Filter operation specification</param>
        /// <returns>An observable collection of historyCollectionSchema items.</returns>
        public ObservableCollection<historyCollectionSchema> Search(FilterSpecification filter)
        {
            return Filter<historyCollectionSchema>.FilterCollection(filter, _data);
        }
	}
}
