// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using WPAppStudio.Entities;
using WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// specialplacesCollection data source.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public class specialplacesCollection : IspecialplacesCollection 
    {
        private readonly ObservableCollection<specialplacesCollectionSchema> _data = new ObservableCollection<specialplacesCollectionSchema>
		{
          new specialplacesCollectionSchema
            {
                Id= new Guid("0e236a70-a3d0-414e-8165-f63165a7f25a"),
                Title=@"[Blog] Bill Reiss' Dev Blog",
                Subtitle=@"http://www.billreiss.com/",
                Image=@"..\Images\Item-1d228416-78eb-4c9d-a686-f96b61540333.png",
                Description=@"Bill Reiss is a Senior Consultant for AgileThought in Tampa, Florida and the Nokia Developer Ambassador for the Southeast USA.",
			},
          new specialplacesCollectionSchema
            {
                Id= new Guid("9037c35f-9863-4094-9f77-8ea7a39f0080"),
                Title=@"[Listserve] Southeast Windows Phone Devs",
                Subtitle=@"http://southeast.devnokia.com/",
                Image=@"..\Images\Item-a589873e-cb0d-4be9-bcc0-fd0748c4283a.png",
                Description=@"Sign up for the Southeast Windows Phone Developers discussion list! It’s a great place to keep tabs on what’s going on and to get technical questions answered by the top developers in the Southeast. You can sign up by filling out the form.",
			},
          new specialplacesCollectionSchema
            {
                Id= new Guid("ebcc5b6c-7678-4008-9046-60b24c3dd85d"),
                Title=@"[Resources] DevFish Wiki",
                Subtitle=@"http://dfwiki.devfish.net/",
                Image=@"..\Images\Item-fd16127a-615d-488a-ac6e-d54f177f8214.png",
                Description=@"Lists and lists of resources. Pretty much all the information you need. Just search for ""Windows Phone"" or ""Windows 8"" or whatever.",
			},
          new specialplacesCollectionSchema
            {
                Id= new Guid("52bff0a8-03da-4231-be4d-5d479141f6fc"),
                Title=@"MDUGJax Meetup",
                Subtitle=@"http://mdugjax.com/",
                Image=@"..\Images\Item-c35724fd-d25f-45ab-b68a-82e338c90d28.png",
                Description=@"Currently, this points to the official Meetup page for MDUGJax. Find more information about upcoming events and make sure you RSVP to them. Get swag!",
			},
		};
	
		
        /// <summary>
        /// Retrieves the data from a static data source, in an observable collection of specialplacesCollectionSchema items.
        /// </summary>
        /// <returns>An observable collection of specialplacesCollectionSchema items.</returns>
        public ObservableCollection<specialplacesCollectionSchema> GetData()
        {		
            return _data;
        }
		
		/// <summary>
        /// Retrieves the data from a static data source, filtered by a filter specification, in an observable collection of specialplacesCollectionSchema items.
        /// </summary>
		/// <param name="filter">Filter operation specification</param>
        /// <returns>An observable collection of specialplacesCollectionSchema items.</returns>
        public ObservableCollection<specialplacesCollectionSchema> Search(FilterSpecification filter)
        {
            return Filter<specialplacesCollectionSchema>.FilterCollection(filter, _data);
        }
	}
}
