// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.Collections.ObjectModel;
using System.Windows.Input;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// linksAboutThisPlace1 ViewModel interface.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public interface IlinksAboutThisPlace1ViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentspecialplacesCollectionSchema property.
        /// </summary>
		specialplacesCollectionSchema CurrentspecialplacesCollectionSchema { get; set; }

	}
}
