// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.Collections.ObjectModel;
using System.Windows.Input;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// upcoming_Detail ViewModel interface.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public interface Iupcoming_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrenthistoryCollectionSchema property.
        /// </summary>
		historyCollectionSchema CurrenthistoryCollectionSchema { get; set; }

        
        /// <summary>
        /// Gets the TextToSpeechupcoming_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechupcoming_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the Shareupcoming_DetailStaticControlCommand command.
        /// </summary>
		ICommand Shareupcoming_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartupcoming_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartupcoming_DetailStaticControlCommand { get; }

	}
}
