// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Windows.Input;
using WPAppStudio;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;
using WPAppStudio.Localization;
using WPAppStudio.Repositories;
using WPAppStudio.Services;
using WPAppStudio.Services.Interfaces;
using WPAppStudio.Shared;
using WPAppStudio.ViewModel.Base;
using WPAppStudio.ViewModel.Interfaces;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of linksAboutThisPlace1 ViewModel.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public partial class linksAboutThisPlace1ViewModel : BindableBase, IlinksAboutThisPlace1ViewModel, INavigable
    {       

		private readonly IDialogService _dialogService;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="linksAboutThisPlace1ViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        public linksAboutThisPlace1ViewModel(IDialogService dialogService)
        {
			_dialogService = dialogService;
        }
		

		private specialplacesCollectionSchema _currentspecialplacesCollectionSchema;

        /// <summary>
        /// CurrentspecialplacesCollectionSchema property.
        /// </summary>		
        public specialplacesCollectionSchema CurrentspecialplacesCollectionSchema
        {
            get
            {
				return _currentspecialplacesCollectionSchema;
            }
            set
            {
                SetProperty(ref _currentspecialplacesCollectionSchema, value);
            }
        }
		public object NavigationContext
        {
            set
            {              
                if (!(value is specialplacesCollectionSchema)) { return; }
                
                CurrentspecialplacesCollectionSchema = value as specialplacesCollectionSchema;
            }
        }
        /// <summary>
        /// Initializes a <see cref="TileInfo" /> object for the linksAboutThisPlace1StaticControl control.
        /// </summary>
		/// <returns>A <see cref="TileInfo" /> object.</returns>
        public TileInfo CreateTileInfolinksAboutThisPlace1StaticControl()
        {
            var tileInfo = new TileInfo
            {
                CurrentId = CurrentspecialplacesCollectionSchema.Id.ToString(),
                Title = CurrentspecialplacesCollectionSchema.Subtitle,
                BackTitle = CurrentspecialplacesCollectionSchema.Subtitle,
                BackContent = CurrentspecialplacesCollectionSchema.Description,
                Count = 0,
                BackgroundImagePath = CurrentspecialplacesCollectionSchema.Image,
                BackBackgroundImagePath = CurrentspecialplacesCollectionSchema.Image,
                LogoPath = "Logo-948b849b-5fc1-4b78-b786-371edeca2d6c.png"
            };
            return tileInfo;
        }
    }
}
