// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Windows.Input;
using WPAppStudio;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;
using WPAppStudio.Localization;
using WPAppStudio.Repositories;
using WPAppStudio.Services;
using WPAppStudio.Services.Interfaces;
using WPAppStudio.Shared;
using WPAppStudio.ViewModel.Base;
using WPAppStudio.ViewModel.Interfaces;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of upcoming_Detail ViewModel.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public partial class upcoming_DetailViewModel : BindableBase, Iupcoming_DetailViewModel, INavigable
    {       

		private readonly IDialogService _dialogService;
		private readonly INavigationService _navigationService;
		private readonly ISpeechService _speechService;
		private readonly IShareService _shareService;
		private readonly ILiveTileService _liveTileService;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="upcoming_DetailViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="speechService">The Speech Service.</param>
        /// <param name="shareService">The Share Service.</param>
        /// <param name="liveTileService">The Live Tile Service.</param>
        public upcoming_DetailViewModel(IDialogService dialogService, INavigationService navigationService, ISpeechService speechService, IShareService shareService, ILiveTileService liveTileService)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_speechService = speechService;
			_shareService = shareService;
			_liveTileService = liveTileService;
        }
		

		private historyCollectionSchema _currenthistoryCollectionSchema;

        /// <summary>
        /// CurrenthistoryCollectionSchema property.
        /// </summary>		
        public historyCollectionSchema CurrenthistoryCollectionSchema
        {
            get
            {
				return _currenthistoryCollectionSchema;
            }
            set
            {
                SetProperty(ref _currenthistoryCollectionSchema, value);
            }
        }

        /// <summary>
        /// Delegate method for the TextToSpeechupcoming_DetailStaticControlCommand command.
        /// </summary>
        public  void TextToSpeechupcoming_DetailStaticControlCommandDelegate() 
        {
	
				_speechService.TextToSpeech(CurrenthistoryCollectionSchema.Subtitle + " " + CurrenthistoryCollectionSchema.Description);
        }
		

        private ICommand _textToSpeechupcoming_DetailStaticControlCommand;

        /// <summary>
        /// Gets the TextToSpeechupcoming_DetailStaticControlCommand command.
        /// </summary>
        public ICommand TextToSpeechupcoming_DetailStaticControlCommand
        {
            get { return _textToSpeechupcoming_DetailStaticControlCommand = _textToSpeechupcoming_DetailStaticControlCommand ?? new DelegateCommand(TextToSpeechupcoming_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the Shareupcoming_DetailStaticControlCommand command.
        /// </summary>
        public  void Shareupcoming_DetailStaticControlCommandDelegate() 
        {
	
				_shareService.Share(CurrenthistoryCollectionSchema.Subtitle, CurrenthistoryCollectionSchema.Description);
        }
		

        private ICommand _shareupcoming_DetailStaticControlCommand;

        /// <summary>
        /// Gets the Shareupcoming_DetailStaticControlCommand command.
        /// </summary>
        public ICommand Shareupcoming_DetailStaticControlCommand
        {
            get { return _shareupcoming_DetailStaticControlCommand = _shareupcoming_DetailStaticControlCommand ?? new DelegateCommand(Shareupcoming_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the PinToStartupcoming_DetailStaticControlCommand command.
        /// </summary>
        public  void PinToStartupcoming_DetailStaticControlCommandDelegate() 
        {
	
				_liveTileService.PinToStart(typeof(Iupcoming_DetailViewModel), CreateTileInfoupcoming_DetailStaticControl());
        }
		

        private ICommand _pinToStartupcoming_DetailStaticControlCommand;

        /// <summary>
        /// Gets the PinToStartupcoming_DetailStaticControlCommand command.
        /// </summary>
        public ICommand PinToStartupcoming_DetailStaticControlCommand
        {
            get { return _pinToStartupcoming_DetailStaticControlCommand = _pinToStartupcoming_DetailStaticControlCommand ?? new DelegateCommand(PinToStartupcoming_DetailStaticControlCommandDelegate); }
        }
		public object NavigationContext
        {
            set
            {              
                if (!(value is historyCollectionSchema)) { return; }
                
                CurrenthistoryCollectionSchema = value as historyCollectionSchema;
            }
        }
        /// <summary>
        /// Initializes a <see cref="TileInfo" /> object for the upcoming_DetailStaticControl control.
        /// </summary>
		/// <returns>A <see cref="TileInfo" /> object.</returns>
        public TileInfo CreateTileInfoupcoming_DetailStaticControl()
        {
            var tileInfo = new TileInfo
            {
                CurrentId = CurrenthistoryCollectionSchema.Id.ToString(),
                Title = CurrenthistoryCollectionSchema.Subtitle,
                BackTitle = CurrenthistoryCollectionSchema.Subtitle,
                BackContent = CurrenthistoryCollectionSchema.Description,
                Count = 0,
                BackgroundImagePath = CurrenthistoryCollectionSchema.Image,
                BackBackgroundImagePath = CurrenthistoryCollectionSchema.Image,
                LogoPath = "Logo-948b849b-5fc1-4b78-b786-371edeca2d6c.png"
            };
            return tileInfo;
        }
    }
}
